version: "3.8"

services:
  database:
    image: mongo:4.4.7
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: app
      MONGO_INITDB_ROOT_PASSWORD: app
    volumes:
      - database:/data/db
    networks:
      - db-network

volumes:
  database:
    driver: local

networks:
  db-network:
    driver: bridge
